# for-loops

for number in [1, 2, 4, 5, 6]
    println(number)
end

# for-loop over a range
# Note, the range is include
for n in 1:2:10
    println(n * 10)
end

N = 1_000_000
for n in 0:100_000:N
    println(n)
end

# for-loops Exercises

# Write a Julia program to construct this pattern below:
# * 
# * * 
# * * * 
# * * * * 
# * * * * * 
# * * * * 
# * * * 
# * * 
# *

rows = [] # empty vector

for r in 1:5
    push!(rows, r)
end

for r in 4:-1:1
    push!(rows, r)
end

for r in rows
    println(repeat("* ", r))
end

# Project Euler Problem 1
# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
# The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.

N = 1_000 - 1  # *below*, not *less or equal than*

acc = 0

for n in 1:N
    if n % 3 == 0 || n % 5 == 0
        acc += n
    end
end

println(acc)

# Project Euler Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

fib = [1, 2]  # we need the first two values
for i in 3:4_000_000  # starting from 3
    v = fib[i - 2] + fib[i - 1]
    if v > 4_000_000
        break
    else
        push!(fib, v)
    end
end

println(fib)
